### ISSUE TITLE
CSS元素居中

### ISSUE THREAD

**Issue by GADLO** [GADLO/markdown#5]
# 水平居中
## 行内元素
父级元素是内联元素时，先设置父级元素为块级元素，再设置父级元素style为：
```css
.parent{
    display: block;
}

.inline {
    text-align: center;
}
```
### 元素有宽度
元素的style为：
```css
.block-child-width {
    margin: 0 auto;
    width: 400px;
}
```
#### 1、父级元素和元素的style为：
```css
.block-parent {
    text-align: center;
}

.block-child {
    /* or display: inline */
    display: inline-block;
}
```
#### 2、父级元素和元素的style为：
```css
.block-parent {
    position: relative;
}

.block-float-child {
    position: absolute;
    left: 50%;
    transform: translate(-50%);
}
```

#### 3、父级元素和元素的style为：
```css
.block-parent {
    display: flex;
    justify-content: center;
}


```
# 垂直居中
### 单行元素
设置父级元素style：
```css
.vertical-center-singleline {
    height: 50px;
    line-height: 50px;
}
```
### 多行元素
```css
设置父级元素style：
.vertical-center-multiline {
    height: 50px;
    display: table-cell;
    vertical-align: middle;
}
```
### 父级元素和元素的style为
```css
  #parent {
        position: relative;
        width: 500px;
        height: 300px;
        background-color: skyblue;
    }
    
    #child {
        position: absolute;
        top: 50%;
        margin-top: -50px;
        height: 100px;
        background-color: green;
    }

```
# 水平垂直居中
```css
.horizon-vertical-center {
    height: 50px;
    display: flex;
    justify-content: center;
    align-items: center;

    /* or
    #parent {
        position: relative;
        width: 500px;
        height: 300px;
        background-color: skyblue;
    }
    
    #child {
        position: absolute;
        background-color: green;
        left: 50%;
        top: 50%;
        transform: translateX(-50%) translateY(-50%);
    }
    */
}
```
